from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
import time

# abre o navegador
driver = webdriver.Chrome()

# entra no site
driver.get("https://game-selenium.netlify.app/missao1/missao1.html")

time.sleep(3)  # espera carregar (simples)

# encontra o botão (exemplo)
btnDireita = driver.find_element(By.ID, "btnDireita")
btnBaixo = driver.find_element(By.ID, "btnBaixo")
missao1 = driver.find_element(By.ID, "missao1")

# clica no botão
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()
btnDireita.click()

btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()

btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()
btnBaixo.click()

btnBaixo.click()
btnBaixo.click()

missao1.click()